import LayoutDashboardIcon from '@/components/movingicons/layoutDashboardIcon'
import LayersIcon from '@/components/movingicons/layersIcon'
import UserIcon from '@/components/movingicons/userIcon'
import UsersIcon from '@/components/movingicons/usersIcon'
import {
  GraduationCap,
  BookOpen,
  ScrollText,
  Grid3x3,
  Clock,
  Star,
  FileText,
  Building2,
  Users,
  Bell,
  BookMarked,
  CalendarDays,
} from 'lucide-react'

const NAV_ITEMS = [
  {
    label: 'Dashboard',
    to: '/dashboard',
    role: ['admin', 'registrar'],
    icon: LayoutDashboardIcon,
  },
  {
    label: 'Dashboard',
    to: '/teacher/dashboard',
    role: ['teacher'],
    icon: LayoutDashboardIcon,
  },
  {
    label: 'Dashboard',
    role: ['student'],
    to: '/student/dashboard',
  },
  {
    label: 'My Subjects',
    role: ['student'],
    to: '/student/subjects',
  },
  {
    label: 'My Profile',
    role: ['student'],
    to: '/student/profile',
  },
  {
    label: 'Materials',
    role: ['student'],
    to: '/student/materials',
    icon: BookMarked,
  },
  {
    label: 'My Grades',
    role: ['student'],
    to: '/student/grades',
    icon: Star,
  },
  {
    label: 'My Schedule',
    role: ['student'],
    to: '/student/schedule',
    icon: Clock,
  },
  {
    label: 'My Attendance',
    role: ['student'],
    to: '/student/attendance',
    icon: CalendarDays,
  },
  {
    label: 'Notifications',
    role: ['student'],
    to: '/notifications',
    icon: Bell,
  },
  {
    label: 'Department',
    to: '/department',
    role: ['admin'],
    icon: LayersIcon,
    group: 'Administration',
  },
  {
    label: 'Account',
    to: '/account',
    role: 'admin',
    icon: UsersIcon,
    group: 'Administration',
  },
  {
    label: 'Program',
    to: '/program',
    role: ['admin'],
    icon: GraduationCap,
    group: 'Academic',
  },
  {
    label: 'Subject',
    to: '/subject',
    role: ['admin', 'registrar', 'teacher'],
    icon: BookOpen,
    group: 'Academic',
  },
  {
    label: 'Enrollment Period',
    to: '/enrollmentperiod',
    role: ['admin', 'registrar'],
    icon: ScrollText,
    group: 'Academic',
  },
  {
    label: 'Curriculum',
    to: '/curriculum',
    role: ['admin', 'registrar', 'teacher'],
    icon: ScrollText,
    group: 'Academic',
  },
  {
    label: 'Sections',
    to: '/section',
    role: ['admin', 'registrar'],
    icon: Grid3x3,
    group: 'Academic',
  },
  {
    label: 'Section Subjects',
    to: '/section-subject',
    role: ['admin', 'registrar'],
    group: 'Academic',
  },
  {
    label: 'Academic Loads',
    to: '/registrar/academic-loads',
    role: ['admin', 'registrar'],
    group: 'Academic',
  },
  {
    label: 'Prerequisites',
    to: '/prerequisites',
    role: 'admin',
    icon: Clock,
    group: 'Academic',
  },
  {
    label: 'Grading Scheme',
    to: '/academic/grading',
    role: ['admin'],
    icon: Star,
    group: 'Academic',
  },
  {
    label: 'Students',
    to: '/student',
    role: ['admin', 'registrar'],
    icon: UserIcon,
    group: 'Students',
  },
  {
    label: 'Applications',
    to: '/admission',
    role: ['registrar', 'admin'],
    icon: FileText,
    group: 'Students',
  },
  {
    label: 'Notifications',
    to: '/notifications',
    role: ['admin', 'registrar'],
    icon: Bell,
  },
  {
    label: 'My Schedule',
    to: '/teacher/schedule',
    role: ['teacher'],
    icon: Clock,
  },
  {
    label: 'Grade Book',
    to: '/teacher/grades',
    role: ['teacher'],
    icon: GraduationCap,
    group: 'Teaching',
  },
  {
    label: 'Materials',
    to: '/teacher/materials',
    role: ['teacher'],
    icon: BookMarked,
    group: 'Teaching',
  },
  {
    label: 'Notifications',
    to: '/notifications',
    role: ['teacher'],
    icon: Bell,
  },
]

export default NAV_ITEMS